"""Provenance seed data for commercial real estate property management domain."""

SEED_SOURCES: tuple[dict, ...] = (
    # NYC Local Laws
    {"canonical_id": "LL97", "family": "NYC Local Law", "authority_level": "regulatory",
     "issuing_body": "NYC Council", "notes": "Climate Mobilization Act — building emissions limits for 25K+ sqft"},
    {"canonical_id": "LL152", "family": "NYC Local Law", "authority_level": "regulatory",
     "issuing_body": "NYC Council", "notes": "Gas piping periodic inspection (4-year cycle by Community District)"},
    {"canonical_id": "LL84", "family": "NYC Local Law", "authority_level": "regulatory",
     "issuing_body": "NYC Council", "notes": "Benchmarking — annual energy and water usage reporting"},
    {"canonical_id": "LL87", "family": "NYC Local Law", "authority_level": "regulatory",
     "issuing_body": "NYC Council", "notes": "Energy audit and retro-commissioning (10-year cycle)"},
    {"canonical_id": "LL11/FISP", "family": "NYC Local Law", "authority_level": "regulatory",
     "issuing_body": "NYC Council", "notes": "Facade Inspection Safety Program (5-year inspection cycle)"},
    {"canonical_id": "LL26", "family": "NYC Local Law", "authority_level": "regulatory",
     "issuing_body": "NYC Council", "notes": "Fire safety and emergency action plan requirements"},
    # NYC agencies and codes
    {"canonical_id": "NYC Zoning Resolution", "family": "NYC Zoning", "authority_level": "regulatory",
     "issuing_body": "NYC DCP", "notes": "Article IV commercial districts C1-C8, use groups I-X"},
    {"canonical_id": "NYC Building Code", "family": "NYC Construction", "authority_level": "regulatory",
     "issuing_body": "NYC DOB", "notes": "Construction codes — building, plumbing, mechanical, fuel gas, energy"},
    {"canonical_id": "HPD Housing Maintenance Code", "family": "NYC Housing", "authority_level": "regulatory",
     "issuing_body": "NYC HPD", "notes": "Residential maintenance standards — heat, hot water, pest control, mold"},
    {"canonical_id": "DHCR Rent Stabilization", "family": "NYC Housing", "authority_level": "regulatory",
     "issuing_body": "NY DHCR", "notes": "Rent stabilization administration for 6+ unit pre-1974 buildings"},
    {"canonical_id": "NYC RGB", "family": "NYC Housing", "authority_level": "regulatory",
     "issuing_body": "NYC RGB", "notes": "Annual rent adjustment guidelines for stabilized units"},
    {"canonical_id": "RPIE", "family": "NYC Tax", "authority_level": "regulatory",
     "issuing_body": "NYC DOF", "notes": "Real Property Income and Expense filing (June 1 deadline, $40K+ assessed value)"},
    # Connecticut
    {"canonical_id": "CT CGS Title 47a", "family": "CT State", "authority_level": "regulatory",
     "issuing_body": "CT General Assembly", "notes": "Connecticut landlord-tenant law"},
    {"canonical_id": "CT Building Code", "family": "CT State", "authority_level": "regulatory",
     "issuing_body": "CT DAS", "notes": "State building code based on IBC/ICC"},
    {"canonical_id": "CT Fire Safety Code", "family": "CT State", "authority_level": "regulatory",
     "issuing_body": "CT DESPP/Fire Marshal", "notes": "Fire safety inspection and compliance"},
    # Arizona
    {"canonical_id": "AZ Landlord Tenant Act", "family": "AZ State", "authority_level": "regulatory",
     "issuing_body": "AZ Legislature", "notes": "ARS Title 33 Chapter 10 — commercial leasing"},
    {"canonical_id": "Scottsdale Zoning", "family": "AZ Municipal", "authority_level": "regulatory",
     "issuing_body": "City of Scottsdale", "notes": "Zoning ordinance and land use regulations"},
    {"canonical_id": "AZ Fire Code", "family": "AZ State", "authority_level": "regulatory",
     "issuing_body": "AZ State Fire Marshal", "notes": "IFC adoption with AZ amendments"},
    # Federal
    {"canonical_id": "ADA", "family": "Federal", "authority_level": "regulatory",
     "issuing_body": "DOJ", "notes": "Americans with Disabilities Act — 2010 Standards for Accessible Design"},
    {"canonical_id": "OSHA", "family": "Federal", "authority_level": "regulatory",
     "issuing_body": "DOL", "notes": "Occupational Safety and Health — workplace safety in building operations"},
    {"canonical_id": "EPA", "family": "Federal", "authority_level": "regulatory",
     "issuing_body": "EPA", "notes": "Environmental compliance — asbestos, lead paint, refrigerant management"},
    {"canonical_id": "Fair Housing Act", "family": "Federal", "authority_level": "regulatory",
     "issuing_body": "HUD", "notes": "Anti-discrimination in residential housing"},
    {"canonical_id": "FASB ASC 842", "family": "Accounting", "authority_level": "regulatory",
     "issuing_body": "FASB", "notes": "Lease accounting standards — landlord and tenant perspectives"},
    # Industry standards
    {"canonical_id": "BOMA Z65.1", "family": "Industry Practice", "authority_level": "industry_practice",
     "issuing_body": "BOMA International", "notes": "Office measurement standard (ANSI/BOMA Z65.1-2017)"},
    {"canonical_id": "COSO ERM", "family": "Risk Framework", "authority_level": "industry_practice",
     "issuing_body": "COSO", "notes": "Enterprise Risk Management framework adapted for commercial real estate"},
    # Credit and risk data providers
    {"canonical_id": "D&B", "family": "Credit Data", "authority_level": "industry_practice",
     "issuing_body": "Dun & Bradstreet", "notes": "Viability Rating, Failure Score, PAYDEX — tenant credit assessment"},
    {"canonical_id": "Equifax CRE", "family": "Credit Data", "authority_level": "industry_practice",
     "issuing_body": "Equifax", "notes": "CRE Tenant Risk Assessment — real-time credit and payment data"},
    {"canonical_id": "Megalytics", "family": "Credit Data", "authority_level": "industry_practice",
     "issuing_body": "Megalytics", "notes": "AI tenant risk scoring — 200 components, Random Forest ML models"},
    # Market data
    {"canonical_id": "CoStar", "family": "Market Data", "authority_level": "informational",
     "issuing_body": "CoStar Group", "notes": "Commercial real estate analytics — 390 markets, daily transaction updates"},
    {"canonical_id": "CompStak", "family": "Market Data", "authority_level": "informational",
     "issuing_body": "CompStak", "notes": "Crowdsourced lease comps — give-to-get data exchange model"},
)
