"""Engram seed definitions for investment analysis tenant.

Two source types:
- eCFR: SEC regulations (Title 17 CFR) — live resolve via eCFR API
- FRED: Economic data series — will resolve via FRED API (requires API key registration)
  For now, FRED engrams serve as rich retrieval cues with summary content.
  Live FRED data integration is a future build (requires fred_client.py).
"""

ENGRAM_SEEDS: tuple[dict, ...] = (
    # ── SEC Regulations (eCFR Title 17) ──
    {
        "label": "17 CFR 240.10b-5: Employment of Manipulative and Deceptive Devices",
        "summary": "The core antifraud rule — prohibits fraud, misrepresentation, and deceit in connection with the purchase or sale of any security",
        "content": "insider trading fraud 10b-5 antifraud misrepresentation material nonpublic information MNPI securities fraud SEC enforcement",
        "cfr_title": 17,
        "cfr_part": "240",
        "cfr_section": "10b-5",
        "authority_level": "regulatory",
        "issuing_body": "Securities and Exchange Commission",
    },
    {
        "label": "17 CFR 243.100: Regulation FD — General Rule",
        "summary": "Prohibits selective disclosure of material nonpublic information by issuers to analysts, institutional investors, or security holders",
        "content": "regulation FD fair disclosure selective disclosure material nonpublic information analyst conference call earnings guidance",
        "cfr_title": 17,
        "cfr_part": "243",
        "cfr_section": "100",
        "authority_level": "regulatory",
        "issuing_body": "Securities and Exchange Commission",
    },
    {
        "label": "17 CFR 240.13a-11: Current Reports on Form 8-K",
        "summary": "Requirements for filing current reports disclosing material events including leadership changes, material agreements, and asset transactions",
        "content": "8-K current report material event leadership change material agreement asset acquisition bankruptcy delisting unregistered securities",
        "cfr_title": 17,
        "cfr_part": "240",
        "cfr_section": "13a-11",
        "authority_level": "regulatory",
        "issuing_body": "Securities and Exchange Commission",
    },
    {
        "label": "17 CFR 240.16a-3: Reporting of Insider Transactions (Form 4)",
        "summary": "Requirements for officers, directors, and 10%+ shareholders to report transactions in company securities within 2 business days",
        "content": "Form 4 insider transaction officer director 10 percent shareholder beneficial ownership reporting Section 16 insider selling buying",
        "cfr_title": 17,
        "cfr_part": "240",
        "cfr_section": "16a-3",
        "authority_level": "regulatory",
        "issuing_body": "Securities and Exchange Commission",
    },
    # ── FRED Economic Data Series (retrieval cues — live data integration pending) ──
    {
        "label": "FRED: Federal Funds Effective Rate (FEDFUNDS)",
        "summary": "The interest rate at which depository institutions lend reserve balances to other depository institutions overnight — the Fed's primary monetary policy tool",
        "content": "federal funds rate FOMC interest rate monetary policy overnight lending rate fed funds effective rate benchmark rate",
        "cfr_title": 0,
        "cfr_part": "FEDFUNDS",
        "cfr_section": "",
        "source_api": "fred",
        "authority_level": "informational",
        "issuing_body": "Federal Reserve Bank of St. Louis",
    },
    {
        "label": "FRED: 10-Year Treasury Constant Maturity Rate (DGS10)",
        "summary": "The yield on 10-year US Treasury securities — the benchmark risk-free rate and key driver of equity valuations and discount rates",
        "content": "10 year treasury yield risk free rate discount rate WACC bond yield duration interest rate sensitivity equity valuation benchmark",
        "cfr_title": 0,
        "cfr_part": "DGS10",
        "cfr_section": "",
        "source_api": "fred",
        "authority_level": "informational",
        "issuing_body": "Federal Reserve Bank of St. Louis",
    },
    {
        "label": "FRED: Consumer Price Index (CPIAUCSL)",
        "summary": "All items consumer price index for all urban consumers — the primary measure of inflation that drives Fed policy and rate expectations",
        "content": "CPI consumer price index inflation headline core inflation purchasing power fed policy rate expectations real return",
        "cfr_title": 0,
        "cfr_part": "CPIAUCSL",
        "cfr_section": "",
        "source_api": "fred",
        "authority_level": "informational",
        "issuing_body": "Bureau of Labor Statistics",
    },
    {
        "label": "FRED: Nonfarm Payrolls (PAYEMS)",
        "summary": "Total nonfarm employment — the most market-moving monthly economic indicator, key signal for labor market health and Fed policy",
        "content": "nonfarm payrolls NFP employment jobs labor market unemployment hiring BLS employment situation report",
        "cfr_title": 0,
        "cfr_part": "PAYEMS",
        "cfr_section": "",
        "source_api": "fred",
        "authority_level": "informational",
        "issuing_body": "Bureau of Labor Statistics",
    },
    {
        "label": "FRED: Real GDP Growth Rate (A191RL1Q225SBEA)",
        "summary": "Real gross domestic product growth rate — the broadest measure of economic output and growth, reported quarterly",
        "content": "GDP gross domestic product real growth rate economic output expansion contraction recession quarter over quarter annualized",
        "cfr_title": 0,
        "cfr_part": "A191RL1Q225SBEA",
        "cfr_section": "",
        "source_api": "fred",
        "authority_level": "informational",
        "issuing_body": "Bureau of Economic Analysis",
    },
    {
        "label": "FRED: 2Y-10Y Treasury Spread (T10Y2Y)",
        "summary": "The difference between 10-year and 2-year Treasury yields — the most watched yield curve indicator, inversion signals recession risk",
        "content": "yield curve spread 2 year 10 year treasury inversion recession indicator term premium rate expectations curve steepening flattening",
        "cfr_title": 0,
        "cfr_part": "T10Y2Y",
        "cfr_section": "",
        "source_api": "fred",
        "authority_level": "informational",
        "issuing_body": "Federal Reserve Bank of St. Louis",
    },
    {
        "label": "FRED: ISM Manufacturing PMI (MANEMP)",
        "summary": "ISM Manufacturing Purchasing Managers Index — leading indicator of economic activity, above 50 signals expansion, below 50 signals contraction",
        "content": "PMI purchasing managers index ISM manufacturing expansion contraction leading indicator new orders production employment",
        "cfr_title": 0,
        "cfr_part": "MANEMP",
        "cfr_section": "",
        "source_api": "fred",
        "authority_level": "informational",
        "issuing_body": "Institute for Supply Management",
    },
    {
        "label": "FRED: CBOE Volatility Index VIX (VIXCLS)",
        "summary": "The VIX measures expected 30-day S&P 500 volatility — the market's fear gauge, key for options pricing and risk assessment",
        "content": "VIX volatility index fear gauge implied volatility S&P 500 options pricing risk sentiment market stress complacency",
        "cfr_title": 0,
        "cfr_part": "VIXCLS",
        "cfr_section": "",
        "source_api": "fred",
        "authority_level": "informational",
        "issuing_body": "Cboe Global Markets",
    },
)
